name = "ishosfactory"
type = "javascript"

[env.production]
name = "ishosfactory"

[build]
command = "pnpm run build"
cwd = "./"

[[kv_namespaces]]
binding = "SESSION"
id = "your_session_kv_namespace_id"
preview_id = "your_preview_session_kv_namespace_id"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "your_images_bucket"
preview_bucket_name = "your_preview_images_bucket"

compatibility_date = "2026-04-10"
compatibility_flags = ["nodejs_compat"]
